common: &common
  adapter: postgresql
  username: postgres
  password: password
  min_messages: ERROR

development:
  <<: *common
  database: calvincrest_development

test:
  <<: *common
  database: calvincrest_test